# syntax=docker/dockerfile:1.1.7-experimental
########################
# Alpine builder image #
########################
FROM golang:1.24.3-alpine3.21 AS build

# Checkout
RUN apk add --no-cache \
        bash \
        git openssh-client \
    && mkdir -p /build \
    && cd /build \
    && git clone https://github.com/layeh/gumble.git \
    && cd gumble \
    && true

# This arg is any valid git reference
# pragma: allowlist nextline secret
ARG GUMBLE_VERSION="146f9205029b73783dbd79043c4fc5247d8c425d"
# Build
RUN cd /build/gumble \
    && git checkout $GUMBLE_VERSION \
    && go build -v -o /build/mumble-ping -buildmode=exe cmd/mumble-ping/main.go \
    && /build/mumble-ping --help \
    && true

#####################
# Alpine ping image #
#####################
FROM alpine:3.21 as ping
COPY --from=build /build/mumble-ping /bin/mumble-ping
COPY ./docker/entrypoint-ping.sh /entrypoint.sh
RUN apk add --no-cache \
        bash \
        coreutils \
    && true
SHELL ["/bin/bash", "-lc"]
ENTRYPOINT ["/entrypoint.sh"]

########################
# Debian builder image #
########################
FROM golang:1.24.3-bookworm AS debianbuild
ENV \
  # locale
  LC_ALL=C.UTF-8 \
  # python:
  PYTHONFAULTHANDLER=1 \
  PYTHONUNBUFFERED=1 \
  PYTHONHASHSEED=random \
  # pip:
  PIP_NO_CACHE_DIR=off \
  PIP_DISABLE_PIP_VERSION_CHECK=on \
  PIP_DEFAULT_TIMEOUT=100 \
  # debconf
  DEBIAN_FRONTEND=noninteractive

# Checkout
RUN mkdir -p /build \
    && cd /build \
    && git clone https://github.com/layeh/gumble.git \
    && cd gumble \
    && true

# This arg is any valid git reference
# pragma: allowlist nextline secret
ARG GUMBLE_VERSION="146f9205029b73783dbd79043c4fc5247d8c425d"
# Build
RUN cd /build/gumble \
    && git checkout $GUMBLE_VERSION \
    && go build -v -o /build/mumble-ping -buildmode=pie cmd/mumble-ping/main.go \
    && /build/mumble-ping --help \
    && true

#####################
# Debian ping image #
#####################
FROM debian:bookworm-slim as debianping
COPY --from=debianbuild /build/mumble-ping /bin/mumble-ping
COPY ./docker/entrypoint-ping.sh /entrypoint.sh
SHELL ["/bin/bash", "-lc"]
ENTRYPOINT ["/entrypoint.sh"]
